# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Videsh
name: Videsh Suman
position: Graduate Student 
affiliation: CICS, UMass Amherst
affiliation_url: https://www.cics.umass.edu/
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
alias: sumanvid97
gmail: videsh.suman@gmail.com
umass_mail: vsuman@cs.umass.edu
github: https://github.com/sumanvid97
linkedin: https://in.linkedin.com/in/sumanvid97
twitter: https://twitter.com/sumanvid97
google_scholar:

kramdown:
  input: GFM